version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build and Test
          command: mvn clean install

      - persist_to_workspace:
          root: ~/repo
          paths:
            - target/

  deploy:
    docker:
      - image: openjdk:11-jre-slim
    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      # Include any additional steps needed for deployment

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # Add deploy job here if needed
